### ISSUE TITLE
Only build test binaries when make check is called

### ISSUE THREAD

**Issue by MeisterEule** [SX-Aurora/Vftrace#11]
The number of test files is increasing, and so is the time spent by make, since all these files are built even when no tests are desired. We should split up the build of the test binaries from the actual Vftrace build.

**Comment by SpinTensor** [comment]
Can be done by replacing `noinst_PROGRAMS` in the test folders `Makefile.am` by `check_PROGRAMS`.
Already did it in the MPI-testsuite branch. Can you adjust it for the unit tests? Thanks, I will close this issue now.

**Comment by MeisterEule** [comment]
Thanks for finding that out. I adapted it for the unit tests as well and it works.
