### ISSUE TITLE
libvftr_{mpi,mpiwrap,pause}.a are built but not installed

### ISSUE THREAD

**Issue by efocht** [SX-Aurora/Vftrace#2]
I can find them in Makefile.am declared like this:
```
noinst_LTLIBRARIES = libvftr_mpi.la \
                     libvftr_mpiwrap.la \
                     libvftr_pause.la
```
so maybe this is on purpose. Unfortunately some symbols from there are needed.

**Comment by MeisterEule** [comment]
This is on purpose - we need different compiler flags for the elements of these libraries. These is done in libtool by creating these auxiliary libraries. They are linked to the final library in the end.

**Comment by efocht** [comment]
What do you mean by:
> They are linked to the final library in the end.

They don't seem to be in libvftrace.a.

**Comment by SpinTensor** [comment]
The content of these libraries is included in the libvftrace. As christian said, they are just a trick to be able to use different compiler flags for specific source code files. We want some files (MPI-wrappers, pause/resume, ...) to be instrumented, but not the rest of vftrace.

```
strings libvftrace.a | grep MPI_Init
strings libvftrace.a | grep vftrace_pause
```

shows that the mpiwrap library as well as the other libs are included.
