### ISSUE TITLE
Update INSTALL instructions on autoreconf

### ISSUE THREAD

**Issue by sbrass** [SX-Aurora/Vftrace#3]
Hey developers,

I have just a small inconvenience (for the uninitiated autotools user).
In order to prepare the configure procedure, the INSTALL should state `autoreconf -i` (the option `-i` is missing). 
With the install option, autoreconf installs all auxiliary files, e.g. `ltmain.sh` and so on, else the autoreconf fails with:
```
configure.ac:88: error: required file './ltmain.sh' not found
autoreconf: automake failed with exit status: 1
```
You may handle this differently, of course.

Another (uncorrelated) suggestion: Could you silence the warning `aclocal: warning: couldn't open directory 'm4': No such file or directory` by providing a dummy m4 directory? However, later on, it's created by autoreconf... So, this is a mere "clean run" fix.

Cheers,
Simon

**Comment by SpinTensor** [comment]
Thanks. The install instructions are updated.
