### ISSUE TITLE
Group functions in profile by name

### ISSUE THREAD

**Issue by SpinTensor** [SX-Aurora/Vftrace#42]
Introduce an environment Variable `VFTR_GROUP_FUNC_PROFS` (?) to optionally group functions with the same name/address into one entry in the profile, independent of their caller, or position in the stack-tree.

**Comment by MeisterEule** [comment]
This is similar to the display functions we have in version 1. Although, they are not displayed in the profile table but below it in a separate entry.

**Comment by SpinTensor** [comment]
Solved!
