### ISSUE TITLE
Check for loop variable initialisation support in configure

### ISSUE THREAD

**Issue by MeisterEule** [SX-Aurora/Vftrace#7]
Oftentimes, the compilation fails because some compilers do not support loop variable initialisation (`for (int i = 0...)`) per default. Rather, they require an explicit `--std=gnu99` flag, or similar. We could check during configuration if this occurs and either supply the corresponding flag autmatically (which might be a bit risky because the names of the flag can differ), or abort the configuration and require the user to add the flag.

**Comment by SpinTensor** [comment]
The flags `-std=gnu11`, `-std=c11`, `-std=c99` are now check in configure until the compiler accepts one. If none is accepted configure aborts with an error message.
