### ISSUE TITLE
autoreconf -i not terminating

### ISSUE THREAD

**Issue by SpinTensor** [SX-Aurora/Vftrace#8]
Currently a freshly cloned vftrace can not be configured as `autoreconf -i` and also `libtoolize` do not terminate.

**Comment by MeisterEule** [comment]
I just cloned the repo and `autoreconf -i` worked fine. So it doesn't happen every time.

**Comment by SpinTensor** [comment]
I just cloned the repo:
```
fuhl@hephaistos software $ git clone git@github.com:SX-Aurora/Vftrace.git vftrace
Cloning into 'vftrace'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 2632 (delta 3), reused 7 (delta 3), pack-reused 2617
Receiving objects: 100% (2632/2632), 545.53 KiB | 337.00 KiB/s, done.
Resolving deltas: 100% (2103/2103), done.
fuhl@hephaistos software $ cd vftrace
fuhl@hephaistos vftrace $ autoreconf -i
aclocal: warning: couldn't open directory ' m4': No such file or directory
aclocal: error: couldn't open directory 'm4': No such file or directory
autoreconf: aclocal failed with exit status: 1
```
So something does not work properly.
I tried to libtoolize it and now it does not terminate.

**Comment by MeisterEule** [comment]
Can confirm. I need to remove the line `AC_CONFIG_MACRO_DIRS([m4])` from `configure.ac` to make it work. I do not know why it worked previously, maybe it's due to an existing global m4 installation?

**Comment by SpinTensor** [comment]
without this line:
```
fuhl@hephaistos vftrace $ autoreconf -i
aclocal: warning: couldn't open directory ' m4': No such file or directory
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
```
I terminated it after 15min.

**Comment by SpinTensor** [comment]
Removing `ACLOCAL_AMFLAGS="-I m4"` from the `Makefile.am` seemed to do the trick. I will close this issue now.
