### ISSUE TITLE
Test binaries are created as Autotools wrappers

### ISSUE THREAD

**Issue by MeisterEule** [SX-Aurora/Vftrace#9]
On some systems, I have observed that the binaries used for unit and MPI testing are created as libtool wrapper scripts. 
They contain this header:
```# test_vftrace - temporary wrapper script for .libs/test_vftrace
# Generated by libtool (GNU libtool) 2.4.2
#
# The test_vftrace program cannot be directly executed until all the libtool
# libraries that it depends on are installed.
``` 
I do not know which dependencies are missing. `automake --add-missing` does not help.

Fortunately, the functionality of the programs is not affected by this. The only obvious difference is that the binary name is `lt-test.x` instead of `test.x`. This does not have an effect on the test results, except for `vftr_filewrite_1`. Here, the names of the output files are compared, which do not match the reference output.

I have currently no idea how this problems originates and how it could be fixed. Further investigation is required.

Possible workaround: In `configure.ac`, check the output of `file test.x`. If it indicates a shell script, mark `vftr_filewrite_1` as `SKIP`.

**Comment by MeisterEule** [comment]
Apparently, this happens on the excact same system, witch the exact same compilers and same libtool version, but for different users.

**Comment by SpinTensor** [comment]
is this still relevant?

**Comment by MeisterEule** [comment]
This has been solved by setting the `VFTR_LOGFILE_BASENAME` in the affected tests, so that the correct reference file is found. The fact that the binaries are wrappers and have prefixes is the normal autotools behavior for shared libraries. For further information, see https://stackoverflow.com/questions/68802851/test-binaries-created-temporary-wrappers.
